BEL.FeedbackWorkflow/BEL.FeedbackWorkflow/BEL.FeedbackWorkflow/Models/Feedbacks/CCActingUserSection.cs
namespace BEL.FeedbackWorkflow.Models.Feedbacks
{
    using BEL.CommonDataContract;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Runtime.Serialization;
    using System.Web;
    using BEL.FeedbackWorkflow.Models.Common;
    using System.ComponentModel.DataAnnotations;
    using BEL.FeedbackWorkflow.Models.Master;
    
    /// <summary>
    /// Feedbacks Detail Section
    /// </summary>
    [DataContract, Serializable]
    public class CCActingUserSection : ISection
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CCActingUserSection"/> class.
        /// </summary>
        public CCActingUserSection()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CCActingUserSection"/> class.
        /// </summary>
        /// <param name="isSet">if set to <c>true</c> [is set].</param>
        public CCActingUserSection(bool isSet)
        {
            if (isSet)
            {
                this.ListDetails = new List<ListItemDetail>() { new ListItemDetail(FeedbackListNames.FEEDBACKLIST, true) };
                this.SectionName = FeedbackSectionName.CCACTINGUSERSECTION;
                this.ApproversList = new List<ApplicationStatus>();
                this.CurrentApprover = new ApplicationStatus();
                this.MasterData = new List<IMaster>();
                this.MasterData.Add(new ApproverMaster());
            }
        }

        /// <summary>
        /// Gets or sets the master data.
        /// </summary>
        /// <value>
        /// The master data.
        /// </value>
        [DataMember, IsListColumn(false), ContainsMasterData(true)]
        public List<IMaster> MasterData { get; set; }

        /// <summary>
        /// Gets or sets the identifier.
        /// </summary>
        /// <value>
        /// The identifier.
        /// </value>
        [DataMember, IsListColumn(false)]
        public int ID { get; set; }

        /// <summary>
        /// Gets or sets the status.
        /// </summary>
        /// <value>
        /// The status.
        /// </value>
        [DataMember]
        public string Status { get; set; }

        /// <summary>
        /// Gets or sets the name of the section.
        /// </summary>
        /// <value>
        /// The name of the section.
        /// </value>
        [DataMember, IsListColumn(false)]
        public string SectionName { get; set; }

        /// <summary>
        /// Gets or sets the form belong to.
        /// </summary>
        /// <value>
        /// The form belong to.
        /// </value>
        [DataMember, IsListColumn(false)]
        public string FormBelongTo { get; set; }

        /// <summary>
        /// Gets or sets the application belong to.
        /// </summary>
        /// <value>
        /// The application belong to.
        /// </value>
        [DataMember, IsListColumn(false)]
        public string ApplicationBelongTo { get; set; }

        /// <summary>
        /// Gets or sets the list details.
        /// </summary>
        /// <value>
        /// The list details.
        /// </value>
        [DataMember, IsListColumn(false)]
        public List<ListItemDetail> ListDetails { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether this instance is active.
        /// </summary>
        /// <value>
        ///   <c>true</c> if this instance is active; otherwise, <c>false</c>.
        /// </value>
        [DataMember, IsListColumn(false)]
        public bool IsActive { get; set; }

        /// <summary>
        /// Gets or sets the action status.
        /// </summary>
        /// <value>
        /// The action status.
        /// </value>
        [DataMember, IsListColumn(false)]
        public ButtonActionStatus ActionStatus { get; set; }

        /// <summary>
        /// Gets or sets the current approver.
        /// </summary>
        /// <value>
        /// The current approver.
        /// </value>
        [DataMember, IsListColumn(false), IsApproverDetails(true, FeedbackListNames.FEEDBACKAPPAPPROVALMATRIX)]
        public ApplicationStatus CurrentApprover { get; set; }

        /// <summary>
        /// Gets or sets the approvers list.
        /// </summary>
        /// <value>
        /// The approvers list.
        /// </value>
        [DataMember, IsListColumn(false), IsApproverMatrixField(true, FeedbackListNames.FEEDBACKAPPAPPROVALMATRIX)]
        public List<ApplicationStatus> ApproversList { get; set; }

        /// <summary>
        /// Gets or sets the button caption.
        /// </summary>
        /// <value>
        /// The button caption.
        /// </value>
        [DataMember, IsListColumn(false)]
        public string ButtonCaption { get; set; }

        /// <summary>
        /// Gets or sets the Forward to Quality.
        /// </summary>
        /// <value>
        /// The Forward to Quality.
        /// </value>
        [DataMember, Required, RequiredOnDraft]
        public bool ForwardtoCCQualityIncharge { get; set; }

        /// <summary>
        /// Gets or sets the Project Type.
        /// </summary>
        /// <value>
        /// The project type.
        /// </value>
        [DataMember, Required, IsPerson(true, true, false), IsViewer]
        public string CCQualityInchargeUser { get; set; }

        /// <summary>
        /// Gets or sets the Project Type.
        /// </summary>
        /// <value>
        /// The project type.
        /// </value>
        [DataMember, IsPerson(true, true, true), FieldColumnName("CCQualityInchargeUser"), IsViewer]
        public string CCQualityInchargeName { get; set; }

        /// <summary>
        /// Gets or sets the files.
        /// </summary>
        /// <value>
        /// The files.
        /// </value>
        [DataMember, IsFile(true)]
        public List<FileDetails> Files { get; set; }

        /// <summary>
        /// Gets or sets the file name list.
        /// </summary>
        /// <value>
        /// The file name list.
        /// </value>
        [DataMember]
        public string CCFileNameList { get; set; }
    }
}

BEL.FeedbackWorkflow/BEL.FeedbackWorkflow/BEL.FeedbackWorkflow/Controllers/Feedbacks/FeedbacksAdminController.cs
namespace BEL.FeedbackWorkflow.Controllers
{
    using BEL.CommonDataContract;
    using BEL.FeedbackWorkflow.BusinessLayer;
    using BEL.FeedbackWorkflow.Common;
    using BEL.FeedbackWorkflow.Models.Common;
    using BEL.FeedbackWorkflow.Models.Feedbacks;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using BEL.FeedbackWorkflow.Models.Master;

    /// <summary>
    /// Feedback Controller
    /// </summary>
    public partial class FeedbacksController : FeedbacksBaseController
    {
        #region "Index"
        /// <summary>
        /// Indexes this instance.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>
        /// Index View
        /// </returns>      
        [SharePointContextFilter]
        public ActionResult FeedbackAdminIndex(int id = 0)
        {
            if (id > 0 && CommonBusinessLayer.Instance.IsAdminUser(this.CurrentUser.UserId))
            {
                FeedbacksAdminContract contract = null;
                Logger.Info("Start Feedback Admin form and ID = " + id);
                Dictionary<string, string> objDict = new Dictionary<string, string>();
                objDict.Add(Parameter.FROMNAME, FormNameConstants.FeedbacksADMINFORM);
                objDict.Add(Parameter.ITEMID, id.ToString());
                objDict.Add(Parameter.USEREID, this.CurrentUser.UserId);
                ViewBag.UserID = this.CurrentUser.UserId;
                ViewBag.UserName = this.CurrentUser.FullName;
                contract = this.GetFeedbacksAdminDetails(objDict);
                contract.UserDetails = this.CurrentUser;

                if (contract != null && contract.Forms != null && contract.Forms.Count > 0)
                {
                    FeedbacksAdminDetailSection feedbackDetailSection = contract.Forms[0].SectionsList.FirstOrDefault(f => f.SectionName == FeedbackSectionName.FEEDBACKDETAILADMINSECTION) as FeedbacksAdminDetailSection;
                    ApplicationStatusSection feedbackApprovalSection = contract.Forms[0].SectionsList.FirstOrDefault(f => f.SectionName == SectionNameConstant.APPLICATIONSTATUS) as ApplicationStatusSection;

                    if (feedbackApprovalSection != null)
                    {
                        feedbackDetailSection.ApproversList = feedbackApprovalSection.ApplicationStatusList;
                        feedbackDetailSection.CCActingUserComments = feedbackDetailSection.ApproversList.FirstOrDefault(p => p.Role == FeedbackRoles.CCACTINGUSER) != null ? feedbackDetailSection.ApproversList.FirstOrDefault(p => p.Role == FeedbackRoles.CCACTINGUSER).Comments : string.Empty;
                        feedbackDetailSection.QualityUserComments = feedbackDetailSection.ApproversList.FirstOrDefault(p => p.Role == FeedbackRoles.QAULITYUSER) != null ? feedbackDetailSection.ApproversList.FirstOrDefault(p => p.Role == FeedbackRoles.QAULITYUSER).Comments : string.Empty;
                        feedbackDetailSection.CCQualityInchargeUserComments = feedbackDetailSection.ApproversList.FirstOrDefault(p => p.Role == FeedbackRoles.CCQUALITYINCHARGEUSER) != null ? feedbackDetailSection.ApproversList.FirstOrDefault(p => p.Role == FeedbackRoles.CCQUALITYINCHARGEUSER).Comments : string.Empty;
                    }
                    return this.View("Admin/FeedbackAdminIndex", contract);
                }
                else
                {
                    return this.RedirectToAction("NotAuthorize", "Master");
                }
            }
            else
            {
                return this.RedirectToAction("NotAuthorize", "Master");
            }
        }
        #endregion

        #region "Save Feedbacks Detail Admin Section"
        /// <summary>
        /// Saves the specified model.
        /// </summary>
        /// <param name="model">The model.</param>
        /// <returns>
        /// Content result
        /// </returns>    
        ////anti forgery attribute removed
        [HttpPost] 
        public ActionResult SaveFeedbacksAdminDetailSection(FeedbacksAdminDetailSection model)
        {
            ActionStatus status = new ActionStatus();
            if (model != null && ModelState.IsValid)
            {
                if (model.ApproversList != null)
                {
                    model.CCActingUser = model.ApproversList.FirstOrDefault(p => p.Role == FeedbackRoles.CCACTINGUSER).Approver;
                    model.CCActingUserName = model.ApproversList.FirstOrDefault(p => p.Role == FeedbackRoles.CCACTINGUSER).ApproverName;
                }
                
                List<FileDetails> fileList = JsonConvert.DeserializeObject<List<FileDetails>>(model.FileNameList);
                if (fileList == null || fileList.Count == 0 || !fileList.Any(m => m.Status != FileStatus.Delete))
                {
                    status.IsSucceed = false;
                    status.Messages = new List<string>() { this.GetResourceValue("Error_FileNameList", System.Web.Mvc.Html.ResourceNames.Feedbacks) };
                    return this.Json(status);
                }
                model.Files = new List<FileDetails>();
                model.Files.AddRange(FileListHelper.GenerateFileBytes(model.FileNameList));
                model.Files.AddRange(FileListHelper.GenerateFileBytes(model.CCFileNameList));
                model.Files.AddRange(FileListHelper.GenerateFileBytes(model.CCQAInchargeFileNameList)); ////For Save Attachemennt
                model.FileNameList = string.Join(",", FileListHelper.GetFileNames(model.FileNameList));
                model.CCFileNameList = string.Join(",", FileListHelper.GetFileNames(model.CCFileNameList));
                model.CCQAInchargeFileNameList = string.Join(",", FileListHelper.GetFileNames(model.CCQAInchargeFileNameList));

                if (model.ApproversList != null)
                {
                    model.ApproversList.FirstOrDefault(p => p.Role == FeedbackRoles.CCACTINGUSER).Comments = model.CCActingUserComments;
                    model.ApproversList.FirstOrDefault(p => p.Role == FeedbackRoles.QAULITYUSER).Comments = model.QualityUserComments;
                    model.ApproversList.FirstOrDefault(p => p.Role == FeedbackRoles.CCQUALITYINCHARGEUSER).Comments = model.CCQualityInchargeUserComments;
                }

                Dictionary<string, string> objDict = this.GetSaveDataDictionary(this.CurrentUser.UserId, model.ActionStatus.ToString(), model.ButtonCaption);
                status = this.SaveSection(model, objDict);
                status = this.GetMessage(status, System.Web.Mvc.Html.ResourceNames.Feedbacks);
            }
            else
            {
                status.IsSucceed = false;
                status.Messages = this.GetErrorMessage(System.Web.Mvc.Html.ResourceNames.Feedbacks);
            }
            return this.Json(status);
        }
        #endregion
    }
}

BEL.FeedbackWorkflow/BEL.FeedbackWorkflow/BEL.FeedbackWorkflow/Controllers/Feedbacks/FeedbacksBaseController.cs
namespace BEL.FeedbackWorkflow.Controllers
{
    using BEL.CommonDataContract;
    using BEL.FeedbackWorkflow.BusinessLayer;
    using BEL.FeedbackWorkflow.Models.Feedbacks;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;

    /// <summary>
    /// Feedbacks Base Controller
    /// </summary>
    public class FeedbacksBaseController : BaseController
    {
        /// <summary>
        /// Get Feedbacks Details
        /// </summary>
        /// <param name="objDict">dictionary parameter</param>
        /// <returns>contract object</returns>
        public FeedbacksContract GetFeedbacksDetails(IDictionary<string, string> objDict)
        {
            FeedbacksContract contract = FeedbacksBusinessLayer.Instance.GetFeedbacksDetails(objDict);
            return contract;
        }

        /// <summary>
        /// Saves the section.
        /// </summary>
        /// <param name="section">The section.</param>
        /// <param name="objDict">The object dictionary.</param>
        /// <returns>return status</returns>
        protected ActionStatus SaveSection(ISection section, Dictionary<string, string> objDict)
        {
            ActionStatus status = new ActionStatus();
            status = FeedbacksBusinessLayer.Instance.SaveBySection(section, objDict);
            return status;
        }

        /// <summary>
        /// Get Feedbacks Admin Form Details
        /// </summary>
        /// <param name="objDict">parameters value</param>
        /// <returns>contract object</returns>
        public FeedbacksAdminContract GetFeedbacksAdminDetails(IDictionary<string, string> objDict)
        {
            FeedbacksAdminContract contract = FeedbacksBusinessLayer.Instance.GetFeedbacksAdminDetails(objDict);
            return contract;
        }

        /// <summary>
        /// Save Feedback Admin Detail Section
        /// </summary>
        /// <param name="section">Section Data</param>
        /// <param name="objDict">parameters value</param>
        /// <returns>Action Status</returns>
        protected ActionStatus SaveFeedbackAdminDetailSection(ISection section, Dictionary<string, string> objDict)
        {
            ActionStatus status = new ActionStatus();
            status = FeedbacksBusinessLayer.Instance.SaveAdminDataBySection(section, objDict);
            return status;
        }

        /// <summary>
        /// Gets all items.
        /// </summary>
        /// <param name="q">The q.</param>
        /// <returns>json string</returns>
        protected string GetAllItemsCode(string q)
        {
            string data = FeedbacksBusinessLayer.Instance.GetAllItemsCode(q);
            return data;
        }

        /// <summary>
        /// Gets Artwork Info
        /// </summary>
        /// <param name="itemCode">The item code.</param>
        /// <returns>json string</returns>
        protected string GetSKUInfoByItemCode(string itemCode)
        {
            string data = FeedbacksBusinessLayer.Instance.GetSKUInfoByItemCode(itemCode);
            return data;
        }
    }
}

BEL.FeedbackWorkflow/BEL.FeedbackWorkflow/BEL.FeedbackWorkflow/Views/Feedbacks/_ProductSerialGrid.cshtml
@using BEL.FeedbackWorkflow.Models.Feedbacks
@using BEL.CommonDataContract
@model List<ITrans>


<div class="table-responsive">
    <table class="table table-hover table-bordered someTable" id="productSerialtable">
        <thead>
            <tr>
                <th>@Html.ResourceValue("Grid_ProductSerial_Header_Label_No", ResourceNames.Feedbacks)</th>
                <th>@Html.ResourceValue("Grid_ProductSerial_Header_Label_ProductSerialNo", ResourceNames.Feedbacks)</th>
                <th>@Html.ResourceValue("Grid_Title_Action", ResourceNames.Common)</th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Count() > 0)
            {
                foreach (ProductSerial item in Model)
                {
                    <tr>

                        <td>@item.Index</td>
                        <td>@item.ProductSerialNo</td>
                        <td>
                            <a class="btn ink-reaction btn-floating-action" data-ajax="true" data-ajax-loading="#loading" data-ajax-method="GET" data-ajax-mode="replace" data-ajax-update="#divAddProductSerial" href="@Url.Action("AddProductSerial","NPD",new {index=@item.Index})">
                                <i class='fa fa-edit'></i>
                            </a>
                            <a class="btn ink-reaction btn-floating-action btn-danger" onclick="ProductSerialDelete('@item.Index');">
                                <i class='fa fa-trash-o'></i>
                            </a>
                        </td>
                    </tr>

                }
            }
            else
            {
                <tr>
                    <td colspan="9" class="text-center text-danger">
                        @Html.ResourceValue("Grid_Text_NoProductSerialData", ResourceNames.NPD)
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

BEL.FeedbackWorkflow/BEL.FeedbackWorkflow/BEL.FeedbackWorkflow/Views/Feedbacks/_ccActingUserSection.cshtml
@using BEL.FeedbackWorkflow.Models.Feedbacks
@using BEL.FeedbackWorkflow.Models.Common
@using BEL.FeedbackWorkflow.Models.Master;
@using BEL.CommonDataContract;
@model CCActingUserSection
@{

    ApproverMaster approverusrelist = Model.MasterData.FirstOrDefault(x => x.NameOfMaster.Equals(FeedbacksMasters.APPROVERMASTER)) as ApproverMaster;
    List<ApproverMasterListItem> ccQualityInchargeUserList = approverusrelist.Items.Where(x => (x as ApproverMasterListItem).Role == FeedbackRoles.CCQUALITYINCHARGEUSER).ToList().ConvertAll(p => (ApproverMasterListItem)p);
    ccQualityInchargeUserList = Helper.SplitUser(ccQualityInchargeUserList);
}

@using (Ajax.BeginForm("SaveCCActingUserSection", "Feedbacks", new AjaxOptions
    {
        HttpMethod = "POST",
        LoadingElementId = "loading",
        OnFailure = "OnFailure",
        OnSuccess = "OnSuccess",
        OnBegin = "BeginClient"
    }, new { enctype = "multipart/form-data" }))
{

    @Html.HiddenFor(m => m.ListDetails[0].ItemId)
    @Html.HiddenFor(m => m.ListDetails[0].ListName)
    @Html.HiddenFor(m => m.SectionName)
    @Html.HiddenFor(m => m.ActionStatus)
    @Html.HiddenFor(m => m.Status)

    @Html.Partial("_ApproversList", Model.ApproversList)
    @*@Html.AntiForgeryToken()*@

    <div class="row">
        <div class="col-sm-6 attachment">
            <div class="form-group">
                <label for="FileNameList" class="col-md-4 control-label">
                    @Html.LabelFor(m => m.CCFileNameList, ResourceNames.Feedbacks)
                </label>
                <div class="col-md-8 ">
                    <span class="text-danger text-default-light">
                        (Max. up to 40MB per file and you can upload maximum 10 files.)
                    </span>
                    <div id="CCAttachFile" data-appname="@SiteURLs.FEEDBACKSITEURL">
                    </div>
                    @Html.TextBoxFor(m => m.CCFileNameList, new { @class = "notvisible" })
                    @Html.ValidationMessageFor(m => m.CCFileNameList, ResourceNames.Feedbacks)

                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                <label class="col-md-4 control-label">
                    <span class="text-danger text-default-light">*</span>
                    @Html.LabelFor(m => m.ForwardtoCCQualityIncharge, ResourceNames.Feedbacks)

                </label>
                <div class="col-md-8 ">
                    <div class="form-control noborder">
                        @Html.RadioButtonFor(m => m.ForwardtoCCQualityIncharge, "True", new { @Id = "ForwardtoQualityIncharge1" })
                        <label for="ForwardtoQualityIncharge1">@Html.ResourceValue("Label_ForwardtoQualityIncharge1", ResourceNames.Feedbacks)</label><br />
                        @Html.RadioButtonFor(m => m.ForwardtoCCQualityIncharge, "False", new { @Id = "ForwardtoQualityIncharge2" })
                        <label for="ForwardtoQualityIncharge2">@Html.ResourceValue("Label_ForwardtoQualityIncharge2", ResourceNames.Feedbacks)</label>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label class="col-sm-4 control-label left">
                    <span class="text-danger text-default-light">*</span>
                    @Html.ResourceValue("Label_Comment", ResourceNames.Feedbacks)
                </label>
                <div class="col-sm-8">
                    <div class="form-control noborder text-left">
                        @Html.TextAreaFor(m => m.CurrentApprover.Comments, new { maxlength = 1000, @class = "form-control requiredOnSendBack", @data_val = "true", @data_val_required = "Comments/Remarks is required (max allow 1000 char.)", data_toggle = "tooltip", title = "Max 1000 characters" })
                        @Html.HiddenFor(x => x.CurrentApprover.Approver)
                        @Html.HiddenFor(x => x.CurrentApprover.Role)
                        @Html.HiddenFor(x => x.CurrentApprover.AssignDate)
                        @Html.ValidationMessageFor(m => m.CurrentApprover.Comments, ResourceNames.Feedbacks)
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group CCQualityInchargeUser">
                <label class="col-md-4 control-label">
                    @*<span class="text-danger text-default-light">*</span>*@
                    @Html.LabelFor(m => m.CCQualityInchargeUser, ResourceNames.Feedbacks)
                </label>
                <div class="col-md-8 ">
                    <div class="form-control noborder">
                       @Html.DisplayFor(m=>m.CCQualityInchargeName)
                      
                        @Html.HiddenFor(m => m.CCQualityInchargeUser)
                        @Html.HiddenFor(m => m.CCQualityInchargeName)
                       

                    </div>
                </div>
            </div>
        </div>

        

    </div>
}

BEL.FeedbackWorkflow/BEL.FeedbackWorkflow/BEL.FeedbackWorkflow/Views/Feedbacks/_ccQualityInchargeSection.cshtml
@using BEL.FeedbackWorkflow.Models.Feedbacks
@using BEL.FeedbackWorkflow.Models.Common
@using BEL.FeedbackWorkflow.Models.Master;
@using BEL.CommonDataContract;
@model CCQualityInchargeSection
@{

    ApproverMaster approverusrelist = Model.MasterData.FirstOrDefault(x => x.NameOfMaster.Equals(FeedbacksMasters.APPROVERMASTER)) as ApproverMaster;
    List<ApproverMasterListItem> qaUserList = approverusrelist.Items.Where(x => (x as ApproverMasterListItem).Role == FeedbackRoles.QAULITYUSER).ToList().ConvertAll(p => (ApproverMasterListItem)p);
    qaUserList = Helper.SplitUser(qaUserList);
}

@using (Ajax.BeginForm("SaveCCQualityInchargeSection", "Feedbacks", new AjaxOptions
    {
        HttpMethod = "POST",
        LoadingElementId = "loading",
        OnFailure = "OnFailure",
        OnSuccess = "OnSuccess",
        OnBegin = "BeginClient"
    }, new { enctype = "multipart/form-data" }))
{

    @Html.HiddenFor(m => m.ListDetails[0].ItemId)
    @Html.HiddenFor(m => m.ListDetails[0].ListName)
    @Html.HiddenFor(m => m.SectionName)
    @Html.HiddenFor(m => m.ActionStatus)
    @Html.HiddenFor(m => m.Status)
    @Html.Partial("_ApproversList", Model.ApproversList)
    @*@Html.AntiForgeryToken()*@

    <div class="row">
        <div class="col-sm-6 attachment">
            <div class="form-group">
                <label for="FileNameList" class="col-md-4 control-label">
                    @Html.LabelFor(m => m.CCQAInchargeFileNameList, ResourceNames.Feedbacks)
                </label>
                <div class="col-md-8 ">
                    <span class="text-danger text-default-light">
                        (Max. up to 40MB per file and you can upload maximum 10 files.)
                    </span>
                    <div id="CCQAAttachFile" data-appname="@SiteURLs.FEEDBACKSITEURL">
                    </div>
                    @Html.TextBoxFor(m => m.CCQAInchargeFileNameList, new { @class = "notvisible" })
                   

                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group">
                <label class="col-md-4 control-label">
                    <span class="text-danger text-default-light">*</span>
                    @Html.LabelFor(m => m.ForwardtoQuality, ResourceNames.Feedbacks)

                </label>
                <div class="col-md-8 ">
                    <div class="form-control noborder">
                        @Html.RadioButtonFor(m => m.ForwardtoQuality, "True", new { @Id = "ForwardtoQuality1" })
                        <label for="ForwardtoQuality1">@Html.ResourceValue("Label_ForwardtoQuality1", ResourceNames.Feedbacks)</label><br />
                        @Html.RadioButtonFor(m => m.ForwardtoQuality, "False", new { @Id = "ForwardtoQuality2" })
                        <label for="ForwardtoQuality2">@Html.ResourceValue("Label_ForwardtoQuality2", ResourceNames.Feedbacks)</label>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label class="col-sm-4 control-label left">
                    <span class="text-danger text-default-light">*</span>
                    @Html.ResourceValue("Label_Comment", ResourceNames.Feedbacks)
                </label>
                <div class="col-sm-8">
                    <div class="form-control noborder text-left">
                        @Html.TextAreaFor(m => m.CurrentApprover.Comments, new { maxlength = 1000, @class = "form-control requiredOnSendBack", @data_val = "true", @data_val_required = "Comments/Remarks is required (max allow 1000 char.)", data_toggle = "tooltip", title = "Max 1000 characters" })
                        @Html.HiddenFor(x => x.CurrentApprover.Approver)
                        @Html.HiddenFor(x => x.CurrentApprover.Role)
                        @Html.HiddenFor(x => x.CurrentApprover.AssignDate)
                        @Html.ValidationMessageFor(m => m.CurrentApprover.Comments, ResourceNames.Feedbacks)
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group qauser">
                <label class="col-md-4 control-label">
                    <span class="text-danger text-default-light">*</span>
                    @Html.LabelFor(m => m.QAUser, ResourceNames.Feedbacks)
                </label>
                <div class="col-md-8 ">
                    <div class="form-control noborder">
                        @Html.ListBox("QAUserList", new MultiSelectList(qaUserList.ToArray(), "UserID", "UserName"), new { @id = "QAUserList", @Name = "QAUserList", @class = "form-control", @data_selected = Model.QAUser })
                        @Html.ValidationMessageFor(m => m.QAUser, ResourceNames.Feedbacks)
                        @Html.ValidationMessage("QAUserList", Html.ResourceValue("Error_Gender", ResourceNames.Feedbacks))
                        @Html.HiddenFor(m => m.QAUser)
                        @Html.HiddenFor(m => m.QAUserName)
                    </div>
                </div>
            </div>
        </div>

        

    </div>
}